In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype=int)
print(arr)

[1 2 3 4 5]


In [ ]:
zeros_arr=np.array([(3,3,4,5),(4,5,3,8)],dtype=float)
print(zeros_arr)
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)

[[3. 3. 4. 5.]
 [4. 5. 3. 8.]]
[[1 1]
 [1 1]]


In [ ]:
arrange_arr=np.arange(5)
print(arrange_arr)

[0 1 2 3 4]


In [ ]:
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [ ]:
sliced_arr=arr[2:4]
print(sliced_arr)

[3 4]


In [ ]:

b=zeros_arr.T
print(b)

[[3. 4.]
 [3. 5.]
 [4. 3.]
 [5. 8.]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [ ]:
b=np.split(a,4)
print(b)

In [ ]:
d=np.linalg.eig(c)
print(d)

EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
data=np.loadtxt("/content/dap sample.txt",dtype=int)
d=np.savetxt("/content/dap sample.txt", data)
print(d)
print(data)

ValueError: the number of columns changed from 6 to 4 at row 2; use `usecols` to select a subset and avoid this error

In [ ]:
import numpy as np
data = np.loadtxt("/content/drive/MyDrive/data set/dap sample.txt", dtype=int,usecols=(0, 1, 2))
d = np.savetxt("/content/date.txt", data)
print(d)
print(data)

None
[[ 1  2  3]
 [ 7  8  9]
 [11 12 13]
 [17 18 19]]


In [ ]:
import numpy as np
data = np.loadtxt("/content/drive/MyDrive/data set/dap sample.txt", dtype=int,usecols=(0, 1, 2))
np.savetxt("/content/date.txt", data)
print(data)

[[ 1  2  3]
 [ 7  8  9]
 [11 12 13]
 [17 18 19]]


In [ ]:
arange_arr=np.arange(0,100,5)
print(arange_arr)
c=np.savetxt("/content/pavani.txt",arange_arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
a=np.random.rand()
print(a)
b=np.random.randint(2,10)
print(b)

0.5543884714798722
4


In [ ]:
a = np.array([[2, 3], [4, 5]])

print(a.ndim)
print(type(a))

2
<class 'numpy.ndarray'>


In [ ]:
a=np.linspace(0.8,2,5)
print(a)


[0.8 1.1 1.4 1.7 2. ]


In [ ]:
a=np.arange(24).reshape(3,2,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.arange(8).reshape(2,2)
b=np.arange(8).reshape(2,2)
print(a@b)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [ ]:
import numpy as np

a = np.arange(8).reshape(2,4)
b = np.arange(8).reshape(2,4)
print(a@b)
print(np.dot(a,b))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a.sum())
print(a.max(axis=1))
b=np.ceil(np.random.rand(2,2))
print(b)
c=np.array([[1,2],[3,4]])
print(c.min())
d=np.array([2,3,5,6,7,8])
d.resize(3,2)
print(d.shape)
print(d)
d.cumsum()

print()

6
[1 1]
[[1. 1.]
 [1. 1.]]
1
(3, 2)
[[2 3]
 [5 6]
 [7 8]]



In [ ]:
a=np.array([1,2,3,4,5,6])
a.resize(2,3)
print(a)
b=np.array([5,6,7,8,9,3])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [5 6 7]
 [8 9 3]]
[[1 2 3 5 6 7]
 [4 5 6 8 9 3]]


In [ ]:
a=np.arange(30).reshape(3,2,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]]


In [ ]:
import numpy as np
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.full((2,2),3)
print(a)
print(a.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3]
a=np.array(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
a=np.array([1.3,4.2,3.5,4.8,6.7,9.7,5.2])
print(np.rint(a))

[ 1.  4.  4.  5.  7. 10.  5.]


In [ ]:
n=np.array([2,3,4,5,6])
p=np.array([1,2,3,4,5])
print(np.true_divide(n,p))

[2.         1.5        1.33333333 1.25       1.2       ]


In [ ]:
n=np.array([1,1,2,3,3,3])
print(np.unique(n))

[1 2 3]


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[4,5,6], [2,5,8]])
print(np.setdiff1d(b,a))

[8]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divide(a,b)
print(c)



[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.multiply(a,b)
print(c)

[ 200  441   60  800 1250 1500]


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[-0.81396021 -0.28894447  0.04031431]
 [ 0.52273017 -0.05893381  1.02152598]]


In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[-1.53194319  1.31973215 -1.51534687]
 [-0.91454715  3.50853652  2.0766591 ]]


In [ ]:
from numpy import random
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[10  5  8  5  7  5  2  7  8  3]


In [ ]:
from numpy import random
x=random.poisson(lam=2,size=10)
print(x)

[2 1 3 1 6 2 1 1 1 2]


In [ ]:
from numpy import random
x=random.choice([2,3,4])
print(x)

3


In [ ]:
from numpy import random
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[5 5 3 3 5]
 [3 3 3 5 5]
 [5 3 3 3 5]]
